swagger: "2.0"
info:
  version: "0.0.1"
  title: Example ALTO Server
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /networkmap/{resourceId}:
    x-swagger-router-controller: alto
    parameters:
    - name: resourceId
      in: path
      description: ID of networkmap to fetch
      required: true
      type: string
    get:
      description: Returns the networkmap by given resource id
      operationId: networkmap
      produces:
      - application/alto-networkmap+json
      - application/alto-error+json
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/networkmap.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
    post:
      description: Reterns the networkmap data by given resource id and a filter
      operationId: networkmap
      consumes:
      - application/alto-networkmapfilter+json
      produces:
      - application/alto-networkmap+json
      - application/alto-error+json
      parameters:
      - name: filter
        in: body
        description: Specifies the filtering parameters as ReqFilteredNetworkmap defined in Sec 11.3.1.3. of RFC7285
        required: true
        schema:
          $ref: "api/swagger/networkmap.yaml#/Request"
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/networkmap.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
  /costmap/{resourceId}:
    x-swagger-router-controller: alto
    parameters:
    - name: resourceId
      in: path
      description: ID of costmap to fetch
      required: true
      type: string
    get:
      description: Returns the costmap by given resource id
      operationId: costmap
      produces:
      - application/alto-costmap+json
      - application/alto-error+json
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/costmap.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
    post:
      description: Reterns the costmap data by given resource id and a filter
      operationId: costmap
      consumes:
      - application/alto-costmapfilter+json
      produces:
      - application/alto-costmap+json
      - application/alto-error+json
      parameters:
      - name: filter
        in: body
        description: Specifies the filtering parameters as ReqFilteredCostmap defined in Sec 11.3.2.3. of RFC7285
        required: true
        schema:
          $ref: "api/swagger/costmap.yaml#/Request"
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/costmap.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
  /endpointcost/{resourceId}:
    x-swagger-router-controller: alto
    parameters:
    - name: resourceId
      in: path
      description: ID of endpoint cost service to lookup
      required: true
      type: string
    post:
      description: Provides information about costs between individual endpoints
      operationId: endpointcost
      consumes:
      - application/alto-endpointcostparams+json
      produces:
      - application/alto-endpointcost+json
      - application/alto-error+json
      parameters:
      - name: filter
        in: body
        description: Specifies the filtering parameters as ReqEndpointCostMap defined in Sec 11.5.1.3. of RFC7285
        required: true
        schema:
          $ref: "api/swagger/endpointcost.yaml#/Request"
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/endpointcost.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
  /endpointprop/{resourceId}:
    x-swagger-router-controller: alto
    parameters:
    - name: resourceId
      in: path
      description: ID of endpoint property service to lookup
      required: true
      type: string
    post:
      description: Provides information about endpoint properties
      operationId: endpointprop
      consumes:
      - application/alto-endpointpropparams+json
      produces:
      - application/alto-endpointprop+json
      - application/alto-error+json
      parameters:
      - name: filter
        in: body
        description: Specifies the filtering parameters as ReqEndpointProp defined in Sec 11.4.1.3. of RFC7285
        required: true
        schema:
          $ref: "api/swagger/endpointproperty.yaml#/Request"
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/endpointproperty.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
  /directory:
    x-swagger-router-controller: alto
    get:
      description: Returns the costmap by given resource id
      operationId: directory
      produces:
      - application/alto-directory+json
      - application/alto-error+json
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/ird.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
  /ext/query/path:
    x-swagger-router-controller: alto_ext
    post:
      description: Returns the next AS hop by flow
      operationId: queryPath
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: flows
        in: body
        required: true
        schema:
          $ref: "api/swagger/path-query.yaml#/Request"
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/path-query.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
  /ext/query/resource:
    x-swagger-router-controller: alto_ext
    post:
      description: Returns resource state abstraction for queried flow set
      operationId: queryResource
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: flows
        in: body
        required: true
        schema:
          $ref: "api/swagger/path-vector.yaml#/Request"
      responses:
        "200":
          description: Success
          schema:
            $ref: "api/swagger/path-vector.yaml#/Response"
        default:
          description: Error
          schema:
            $ref: "api/swagger/error.yaml#/Error"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
