swagger: "2.0"
info:
  version: "0.1.0"
  title: Basic Data Type of Unicorn
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
paths: {}
definitions:
  FlowSpec:
    required:
    - srcIP
    - dstIP
    properties:
      srcIP:
        type: string
        pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
      dstIP:
        type: string
        pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
  QueryDesc:
    required:
    - flow
    - ingress-point
    properties:
      flow:
        $ref: "#/definitions/FlowSpec"
      ingress-point:
        type: string
        pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
  VectorArray:
    type: array
    items:
      type: array
      items:
        type: integer
