swagger: "2.0"
info:
  version: "0.1.0"
  title: Resource Query Type of Unicorn
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
paths: {}
definitions:
  ANE:
    type: object
    required:
    - availbw
    properties:
      availbw:
        type: integer
        format: int32
      example:
        availbw: 1000000
  ANEFlowCoefficient:
    type: object
    required:
    - flow-id
    properties:
      flow-id:
        type: integer
        format: int32
      coefficient:
        type: number
        format: double
    example:
      flow-id: 0
      coefficient: 0.5
  ResourceQueryResponse:
    type: object
    required:
    - ane-matrix
    - anes
    properties:
      ane-matrix:
        type: array
        items:
          type: array
          items:
            $ref: "#/definitions/ANEFlowCoefficient"
      anes:
        type: array
        items:
          $ref: "#/definitions/ANE"
      example:
        ane-matrix:
        - - flow-id: 1
            coefficient: 0.5
          - flow-id: 2
            coefficient: 1
        - - flow-id: 1
            coefficient: 0.5
        anes:
        - availbw: 1000000
        - availbw: 700000
