swagger: "2.0"
info:
  version: "0.1.0"
  title: Example Unicorn Server (An ALTO Extension)
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
basePath: /v1/unicorn
paths:
  /ext/query/path:
    post:
      description: Make a recursive path query
      operationId: queryPath
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: query-set
        required: true
        schema:
          type: array
          description: >
            each item provides the specifications of a flow and from where it will
            enter the current domain.
          items:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/ext/basic.yaml#/definitions/QueryDesc"
      responses:
        200:
          description: Success
          schema:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/ext/path-query.yaml#/definitions/PathQueryResponse"
        default:
          description: Error
          schema:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/error.yaml#/definitions/Error"
  /ext/query/resource:
    post:
      description: Returns resource state abstraction in simple mode
      operationId: queryResource
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: query-set
        in: body
        required: true
        schema:
          type: array
          description: >
            each item provides the specifications of a flow and from where it will
            enter the current domain.
          items:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/ext/basic.yaml#/definitions/QueryDesc"
      responses:
        200:
          description: Success
          schema:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/ext/resource-query.yaml#/definitions/ResourceQueryResponse"
        default:
          description: Error
          schema:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/error.yaml#/definitions/Error"
