swagger: "2.0"
info:
  version: "0.1.0"
  title: CostMap Type of ALTO
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
paths: {}
definitions:
  Request:
    properties:
      constraints:
        $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/Constraints"
      cost-type:
        $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/CostType"
      pids:
        properties:
          srcs:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/Pids"
          dsts:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/Pids"
        required:
        - srcs
        - dsts
        type: object
    required:
    - cost-type
    - pids
    type: object
  Response:
    properties:
      meta:
        id: /properties/meta
        properties:
          cost-type:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/CostType"
          dependent-vtags:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/DependentVtags"
        required:
        - dependent-vtags
        - cost-type
        type: object
      cost-map:
        id: /properties/cost-map
        patternProperties:
          ^[0-9a-zA-Z-:@_\.]{1,64}$:
            id: /properties/cost-map/patternProperties/src
            patternProperties:
              ^[0-9a-zA-Z-:@_\.]{1,64}$:
                id: /properties/cost-map/patternProperties/src/patternProperties/dst
            type: object
        type: object
    required:
    - meta
    - cost-map
    type: object
